version: "3.3"
services:
    db:
        image: postgres:11
        container_name: tasksdb
        ports:
            - 5433:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            PGDATA : /var/lib/postgresql/data
        volumes:
            - data:/var/lib/postgresql/data
    
volumes: 
    data: 
        driver: local



        
